# Generated by Django 2.2 on 2020-07-07 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('45e4e90e-e537-4f69-a03e-98ddb758095d')),
        ),
        migrations.AlterModelTable(
            name='user',
            table='lipotes_user',
        ),
    ]
