# Generated by Django 2.2 on 2020-09-02 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('294f0055-a778-4d0e-90eb-3289f9f15470')),
        ),
    ]
