# Generated by Django 2.2 on 2020-08-19 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200707_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('35c659bb-236b-43db-bba6-9d7d641d64c7')),
        ),
    ]
