# Generated by Django 2.2 on 2020-09-02 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200902_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('4c834fd3-c5ba-4b8a-a269-66cb73b12a40')),
        ),
    ]
