# Generated by Django 2.2 on 2020-09-02 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200902_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('2294acf4-4770-40cd-9479-ebfdab4084af')),
        ),
    ]
