# Generated by Django 2.2 on 2020-08-19 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200819_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('43538efa-2c74-4e54-ab71-7a17930c03d8')),
        ),
    ]
