# Generated by Django 2.2 on 2020-08-19 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200819_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('6071ba87-939d-46a2-b528-cbea82bfc8b3')),
        ),
        migrations.AlterModelTable(
            name='user',
            table='flow_user',
        ),
    ]
