# Generated by Django 2.2 on 2020-08-19 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200819_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('c5b070ac-5ee2-46a9-87ff-3155faf0d6df')),
        ),
    ]
