# Generated by Django 2.2 on 2020-08-19 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200819_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('6ba23d1c-590e-4848-9bf6-8c5545f60cba')),
        ),
    ]
