# Generated by Django 2.2 on 2020-08-19 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200819_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('39fd476a-20db-499c-943e-c612bac6a842')),
        ),
    ]
