# Generated by Django 2.2 on 2020-08-19 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200819_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('3ad0f853-a72d-4f40-a0a2-9b41f132bbef')),
        ),
    ]
