# Generated by Django 2.2 on 2020-08-21 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200819_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('60678b9c-e6a5-4d35-8022-1dcb9ccf270b')),
        ),
    ]
