# Generated by Django 2.2 on 2020-08-24 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200821_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('c3c2911e-5852-48d1-9105-fb2912af6aba')),
        ),
    ]
