# Generated by Django 2.2 on 2020-08-24 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200824_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('3518367e-f40a-481d-b053-d0e1b1593862')),
        ),
    ]
