# Generated by Django 2.2 on 2020-08-25 03:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200824_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('ac5ec9f1-c41a-4f27-8fb5-d1fc9a9ae672')),
        ),
    ]
