# Generated by Django 2.2 on 2020-08-25 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200825_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('b7dc26e5-b906-4364-8523-ef8979d126bc')),
        ),
    ]
