# Generated by Django 2.2 on 2020-09-02 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200825_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('8a85a838-f631-4307-8b9e-6c311929436f')),
        ),
    ]
