# Generated by Django 2.2 on 2020-09-02 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200902_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('1c2a7acf-dd86-4140-8e6b-8f9430a70517')),
        ),
    ]
