# Generated by Django 2.2 on 2020-09-02 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200902_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('852eaed9-a84a-47fd-b0ac-01b2375601e3')),
        ),
    ]
