# Generated by Django 2.2 on 2020-09-02 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200902_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('db6cf7ec-bbbf-48b5-83ba-a5a3727f5371')),
        ),
    ]
