# Generated by Django 2.2 on 2020-09-02 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200902_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('30be95a8-4728-4e96-8357-8169ab6db5a0')),
        ),
    ]
