# Generated by Django 2.2 on 2020-09-02 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200902_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('8f910b76-f112-4ae9-bf89-4d531ad0c742')),
        ),
    ]
