# Generated by Django 2.2 on 2020-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPMN20XML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_key', models.CharField(max_length=32, unique=True)),
                ('flow_uniq_key', models.CharField(max_length=32)),
                ('bpmn_content', models.TextField()),
                ('version', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 't_flow_bpmn20xml',
                'verbose_name_plural': 'bpmn20xml内容',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FlowCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_key', models.CharField(max_length=32, unique=True)),
                ('annotation', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 't_flow_category',
                'verbose_name_plural': '流程分类定义，便于维护',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FlowDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_key', models.CharField(max_length=32, unique=True)),
                ('uniq_name', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(max_length=32)),
                ('online_bpmn_key', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('online', '生效'), ('offline', '下线'), ('del', '删除')], default='draft', max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('mtime', models.DateTimeField(auto_now_add=True, help_text='修改时间')),
            ],
            options={
                'verbose_name': 't_flow_definition',
                'verbose_name_plural': '流程基本信息定义',
                'ordering': ['-id'],
            },
        ),
    ]
