# Generated by Django 2.2 on 2020-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(default='', max_length=50)),
                ('pkey', models.CharField(max_length=255)),
                ('pname', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('bpmn2', models.TextField()),
            ],
            options={
                'verbose_name': 'ProcessDefinition',
                'verbose_name_plural': '流程定义',
                'ordering': ['-id'],
            },
        ),
    ]
