# Generated by Django 2.2 on 2020-09-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowdefinition',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='version_id',
            field=models.CharField(max_length=64, null=True, verbose_name='流程定义版本ID'),
        ),
    ]
