# Generated by Django 2.2 on 2020-06-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdefinition',
            name='status',
            field=models.CharField(choices=[('draf', '草稿'), ('on', '生效'), ('off', '下线'), ('del', '删除')], default='draft', max_length=255),
        ),
    ]
