# Generated by Django 2.2 on 2020-09-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0002_auto_20200902_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdefinition',
            name='version_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='流程定义版本ID'),
        ),
    ]
