# Generated by Django 2.2 on 2020-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0003_auto_20200819_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdefinition',
            name='extend_fields',
            field=models.TextField(default={}),
        ),
    ]
