# Generated by Django 2.2 on 2020-08-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0004_flowdefinition_extend_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmn',
            name='process_definition_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
