# Generated by Django 2.2 on 2020-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0005_bpmn_process_definition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmn',
            name='process_definition_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
