# Generated by Django 2.2 on 2020-08-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0006_auto_20200819_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpmn',
            old_name='process_definition_id',
            new_name='flowable_id',
        ),
    ]
