# Generated by Django 2.2 on 2020-08-21 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0008_auto_20200821_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowcategory',
            old_name='annotation',
            new_name='uname',
        ),
    ]
