# Generated by Django 2.2 on 2020-08-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0009_auto_20200821_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowinstance',
            name='uid',
            field=models.CharField(default=123, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bpmn',
            name='flow_uid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bpmn',
            name='flowable_id',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bpmn',
            name='uid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='bpmn',
            name='version',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='flowcategory',
            name='uid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='flowcategory',
            name='uname',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='bpmn_uid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='uid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='flowinstance',
            name='bpmn_uid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='flowinstance',
            name='flowable_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='flowinstance',
            name='start_user_id',
            field=models.CharField(max_length=32),
        ),
    ]
