# Generated by Django 2.2 on 2020-08-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0010_auto_20200824_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowinstance',
            name='flowable_id',
        ),
    ]
