# Generated by Django 2.2 on 2020-08-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0011_remove_flowinstance_flowable_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('taskDefinitionKey', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'task_instance',
                'verbose_name_plural': 'task_instances',
                'db_table': 'task_inst',
                'ordering': ['-id'],
            },
        ),
    ]
