# Generated by Django 2.2 on 2020-08-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0012_taskinstance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flowinstance',
            table='flow_inst',
        ),
    ]
