# Generated by Django 2.2 on 2020-09-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0013_auto_20200825_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpmn',
            options={'ordering': ['-id'], 'verbose_name': 'flow_definition_version', 'verbose_name_plural': 'flow_definition_versions'},
        ),
        migrations.AlterModelOptions(
            name='flowcategory',
            options={'ordering': ['-id'], 'verbose_name': 'flow_definition_category', 'verbose_name_plural': 'flow_definition_categories'},
        ),
        migrations.AlterModelOptions(
            name='flowdefinition',
            options={'ordering': ['-id'], 'verbose_name': 'flow_definitions', 'verbose_name_plural': '流程定义'},
        ),
        migrations.AlterModelTable(
            name='bpmn',
            table='flow_definition_version',
        ),
        migrations.AlterModelTable(
            name='flowcategory',
            table='flow_definition_category',
        ),
    ]
