# Generated by Django 2.2 on 2020-09-02 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flow_manage', '0015_auto_20200902_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmn',
            name='id',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='流程定义bpmn版本ID'),
        ),
        migrations.AlterField(
            model_name='flowcategory',
            name='id',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='流程分类ID'),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='id',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='流程定义ID'),
        ),
        migrations.AlterField(
            model_name='flowinstance',
            name='id',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='流程实例ID'),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='id',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='任务实例ID'),
        ),
    ]
