# Generated by Django 2.2 on 2020-09-07 06:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowbpmn',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_flow', to='flows.Flow', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='mtime',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='uuid',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=64, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='bpmn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='flows.FlowBpmn', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='flows.FlowCategory', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='mtime',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='flowbpmn',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True),
        ),
        migrations.AlterField(
            model_name='flowbpmn',
            name='mtime',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='flowcategory',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True),
        ),
        migrations.AlterField(
            model_name='flowcategory',
            name='mtime',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='flowinstance',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True),
        ),
        migrations.AlterField(
            model_name='flowinstance',
            name='mtime',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', null=True),
        ),
    ]
