# Generated by Django 2.2 on 2020-09-09 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_auto_20200907_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinstance',
            old_name='create_time',
            new_name='flowable_created_time',
        ),
        migrations.AddField(
            model_name='flowinstance',
            name='flow_bpmn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_bpmn', to='flows.FlowBpmn', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='flow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_flow_instance', to='flows.FlowInstance', to_field='uuid'),
        ),
    ]
