# Generated by Django 2.2 on 2020-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0003_auto_20200909_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinstance",
            name="flowable_process_instance_id",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
