# Generated by Django 2.2 on 2020-09-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0012_formcontent_form_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formcontent",
            old_name="form_content",
            new_name="form",
        ),
    ]
